'use strict';

document.addEventListener('DOMContentLoaded', () => {
    
const NAV_LINKS = [
  { href: '#home', label: 'Home' },
  { href: '#about-us', label: 'About Us' },
  { href: '#services', label: 'Services' },
  { href: '#destinations', label: 'Destinations' },
  { href: '#impact', label: 'Success Stories' },
  { href: '#how', label: 'How It Works' },
  { href: '#testimonials', label: 'Testimonials' },
  { href: '#contact', label: 'Contact' }
];

const desktopNav = document.getElementById('desktopNav');
const mobileNav = document.getElementById('mobileNav');
const footerNav = document.getElementById('footerNav');
if (desktopNav && mobileNav && footerNav) {
  desktopNav.innerHTML = NAV_LINKS.map(({ href, label }) => `<li><a class="nav-link" href="${href}">${label}</a></li>`).join('');
  mobileNav.innerHTML = NAV_LINKS.map(({ href, label }) => `<a class="mobile-link" href="${href}">${label}</a>`).join('');
  footerNav.innerHTML = NAV_LINKS.map(({ href, label }) => `<li><a href="${href}">${label}</a></li>`).join('');
}

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin);

    const destinations = [
      { key:'usa',name:'USA',flag:'🇺🇸',image:'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1400&q=80',pulse:'94%',why:'The USA offers globally ranked universities, high research funding, and diverse career pathways across STEM, business, and creative fields.',scholarships:'Merit scholarships, assistantships, athletics, Fulbright, and departmental fellowships.',work:'Part-time up to 20 hrs/week during studies, OPT/CPT post-study routes, typical graduate salaries vary by field from ~$55k-$120k.',stability:'Stable institutions, deep innovation economy, and strong long-term education investment.',life:'High living cost in major cities; dynamic campus culture and extensive student communities.',unis:[['Harvard University (#4)','Ivy League leader in law, business, and policy. Alumni: Barack Obama.'],['Stanford University (#6)','Innovation powerhouse in Silicon Valley. Alumni: Sundar Pichai.'],['MIT (#1)','Top engineering and technology institution. Alumni: Kofi Annan.'],['NYU (#38)','Global urban campus in New York City. Alumni: Lady Gaga.']] },
      { key:'italy',name:'Italy',flag:'🇮🇹',image:'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1400&q=80',pulse:'96%',why:'Italy combines historic universities, world-class design and architecture ecosystems, and strong access to broader EU opportunities.',scholarships:'DSU regional grants, merit awards, tuition waivers, and Erasmus mobility support.',work:'Part-time work allowed during studies, with increasing opportunities in design, engineering, and tourism sectors.',stability:'EU framework, stable academic system, and expanding international education strategy.',life:'Moderate living costs outside Milan/Rome; rich culture and strong student lifestyle.',unis:[['University of Bologna (#154)','Historic institution with broad academic strength. Alumni: Copernicus.'],['Politecnico di Milano (#111)','Top engineering and design university. Alumni: Renzo Piano.'],['Sapienza University of Rome (#134)','Large research university with international programs.'],['University of Padua (#219)','Strong science and medicine legacy. Alumni: Galileo Galilei.']] },
      { key:'austria',name:'Austria',flag:'🇦🇹',image:'https://images.travelandleisureasia.com/wp-content/uploads/sites/5/2024/01/23175521/halstatt.jpeg',pulse:'95%',why:'Austria offers high quality of life, respected public universities, and a strategic location in central Europe for mobility and networking.',scholarships:'OeAD grants, mobility scholarships, tuition subsidies, and university merit support.',work:'Part-time options for students; strong graduate opportunities in engineering, research, and health sectors.',stability:'Politically stable EU nation with resilient economy and strong social systems.',life:'Balanced living costs, clean cities, and excellent transport infrastructure.',unis:[['University of Vienna (#130)','Historic institution across humanities and sciences. Alumni: Sigmund Freud.'],['TU Wien (#190)','Leading technology and engineering university.'],['Medical University of Vienna (#90 Medicine)','Globally respected medical training and research.'],['WU Vienna (#47 Business Masters)','Top business-focused university in Europe.']] },
      { key:'china',name:'China',flag:'🇨🇳',image:'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1400&q=80',pulse:'93%',why:'China blends top-ranked universities, advanced technology ecosystems, and expanding scholarship channels for international students.',scholarships:'CSC scholarships, provincial grants, university scholarships, and bilateral programs.',work:'Part-time rules vary by city/institution; post-study opportunities are strongest in tech and manufacturing hubs.',stability:'Large diversified economy with strong infrastructure and long-term education investment.',life:'Affordable to premium cost range by city; fast-paced urban student experience.',unis:[['Tsinghua University (#20)','Elite engineering and policy institution. Alumni: Xi Jinping.'],['Peking University (#14)','Comprehensive top-ranked academic leader.'],['Fudan University (#39)','Strong in business, medicine, and social sciences.'],['Shanghai Jiao Tong (#45)','High-impact engineering and innovation programs.']] },
      { key:'france',name:'France',flag:'🇫🇷',image:'https://images.unsplash.com/photo-1431274172761-fca41d930114?auto=format&fit=crop&w=1400&q=80',pulse:'95%',why:'France delivers globally respected degrees, research excellence, and prestigious institutions across arts, sciences, and engineering.',scholarships:'Eiffel scholarships, CROUS support, campus grants, and merit-based tuition discounts.',work:'Students can work part-time; post-study permits support career transition in multiple sectors.',stability:'Stable democratic institutions and a strong, diversified economy.',life:'Paris is premium-cost; other cities are moderate with rich student culture and transport.',unis:[['Sorbonne University (#63)','High-impact research in sciences and humanities. Alumni: Marie Curie.'],['École Polytechnique (#38)','Elite STEM grande école with global profile.'],['Sciences Po (#=3 Politics)','Top social sciences and policy school.'],['Université PSL (#24)','Research-intensive federation of elite schools.']] },
      { key:'germany',name:'Germany',flag:'🇩🇪',image:'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1400&q=80',pulse:'97%',why:'Germany is renowned for engineering, applied research, and strong pathways from study to employment in Europe’s largest economy.',scholarships:'DAAD scholarships, foundations, industry-linked grants, and university fellowships.',work:'Student part-time rights are strong; post-study residence options are established and practical.',stability:'High economic resilience, strong institutions, and industrial leadership.',life:'Moderate living costs in many cities, excellent public transit, and safe student environments.',unis:[['Technical University of Munich (#37)','Global technical leader. Alumni: Rudolf Diesel.'],['Heidelberg University (#87)','Germany’s oldest research university.'],['LMU Munich (#59)','Strong cross-disciplinary research profile.'],['RWTH Aachen (#106)','Top engineering and applied science institution.']] },
      { key:'uk',name:'UK',flag:'🇬🇧',image:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1400&q=80',pulse:'94%',why:'The UK offers globally recognized degrees, intensive one-year master programs, and strong employer reputation worldwide.',scholarships:'Chevening, Commonwealth, GREAT scholarships, and university-specific merit awards.',work:'Part-time work during studies and Graduate Route post-study work options are widely used.',stability:'Stable institutions, sophisticated economy, and global business connectivity.',life:'Higher costs in London; vibrant campus life and broad multicultural communities.',unis:[['University of Oxford (#3)','Historic global academic leader. Alumni: Malala Yousafzai.'],['University of Cambridge (#5)','World-class research and tutorial model. Alumni: Isaac Newton.'],['Imperial College London (#2)','STEM-focused excellence in central London.'],['UCL (#9)','Major multidisciplinary research university.']] },
      { key:'romania',name:'Romania',flag:'🇷🇴',image:'https://media.cntravellerme.com/photos/686fba121f3b9dd9d1a32715/16:9/w_2560%2Cc_limit/481284732',pulse:'92%',why:'Romania provides affordable European education, growing English-taught programs, and strong value-for-cost for international students.',scholarships:'Romanian Government scholarships, university merit awards, and bilateral funding routes.',work:'Part-time student opportunities and expanding entry-level jobs in IT, services, and engineering.',stability:'EU member with steady growth and improving academic internationalization.',life:'Lower living costs compared with many EU capitals; welcoming student cities like Cluj and Bucharest.',unis:[['University of Bucharest (#=801)','Historic comprehensive university in the capital.'],['Babeș-Bolyai University (#=781)','Top multicultural university in Cluj-Napoca.'],['Politehnica University of Bucharest (#=1200)','Leading engineering institution.'],['Alexandru Ioan Cuza University (#=1200)','Respected public research university.']] }
    ];

    const testimonialsData = [
      {img:'https://cdn.pixabay.com/photo/2024/02/18/12/08/ai-generated-8581078_1280.jpg',name:'Liya M.',country:'Italy',q:'Broad Mobility gave me clear, step-by-step support from consultation to approval.'},
      {img:'https://img.freepik.com/premium-photo/portrait-male-student-standing-outside-front-college-buildingcreated-with-generative-ai-technology_132358-9085.jpg',name:'Abel T.',country:'Germany',q:'Exceptional interview coaching and documentation quality improved my confidence.'},
      {img:'https://img.freepik.com/premium-photo/academic-pursuits-young-asian-indian-college-students-studying-generative-ai_94628-12529.jpg',name:'Sara K.',country:'UK',q:'Professional communication and fast response throughout the entire process.'},
      {img:'https://cdn.makifaa.com/v450/etudiant-souriant-avec-son-sac-au-dos-et-ses-documents-mg5wbu.jpg',name:'Nahom B.',country:'France',q:'Their global strategy helped me choose the right destination and timeline.'},
      {img:'https://static.vecteezy.com/system/resources/thumbnails/041/509/704/small/ai-generated-asian-female-student-at-university-campus-young-refugee-woman-with-backpack-concept-of-immigrant-education-refugee-integration-diversity-cultural-exchange-academic-aspiration-photo.jpeg',name:'Bethel R.',country:'Austria',q:'Truly premium guidance with practical scholarship and visa preparation advice.'},
      {img:'https://img.freepik.com/free-photo/front-view-young-man-walking-university-with-black-bag_140725-34762.jpg?semt=ais_rp_progressive&w=740&q=80',name:'Yosef G.',country:'USA',q:'The visa pathway became simple and structured with clear milestones at every step.'},
      {img:'https://img.freepik.com/premium-photo/happy-brazilian-lady-student-casual-with-backpack-holding-books-smartphone-university_116547-60250.jpg?semt=ais_hybrid&w=740&q=80',name:'Selam A.',country:'Romania',q:'Fast response and transparent communication made every stage stress-free.'},
      {img:'https://img.freepik.com/premium-photo/young-smiling-student-graduation-dressed-ai-generative_955712-5349.jpg',name:'Mikias D.',country:'China',q:'Outstanding country strategy and interview preparation helped me succeed confidently.'},
      {img:'https://img.freepik.com/premium-photo/portrait-happy-beautiful-graduate-girl-with-graduation-gown-cap_670421-7887.jpg',name:'Hana K.',country:'France',q:'Professional support from Addis Ababa to final approval with international standards.'},
    ];

    const mkTestiCard = t => `<article class="glass rounded-2xl p-5 border-2 border-accent/70 min-w-[320px] max-w-[320px]"><div class="text-4xl text-accent leading-none">“</div><div class="mt-2 text-gold">★★★★★</div><p class="mt-3 text-sm text-gray-700">${t.q}</p><div class="mt-4 flex items-center gap-3"><img src="${t.img}" class="w-12 h-12 rounded-full object-cover" loading="lazy" alt="${t.name}"><p class="text-sm font-bold text-accent">${t.name} • ${t.country}</p></div></article>`;
    const loopCards = [...testimonialsData, ...testimonialsData].map(mkTestiCard).join('');
    homeTestiTop.innerHTML = loopCards; homeTestiBottom.innerHTML = loopCards;

    const grid = document.getElementById('destinationGrid');
    destinations.forEach((d,idx)=>{ const tall = idx===0||idx===3 ? 'sm:row-span-2' : ''; grid.insertAdjacentHTML('beforeend', `<article class="country-card reveal ${tall} relative rounded-2xl overflow-hidden transition duration-500 cursor-pointer" data-country="${d.key}"><img class="country-image absolute inset-0 w-full h-full object-cover" src="${d.image}" alt="${d.name}" loading="lazy"/><div class="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"></div><div class="absolute bottom-4 left-4 text-white"><h3 class="font-semibold text-xl">${d.name} ${d.flag}</h3><p class="country-pulse text-sm">Success Pulse: ${d.pulse}</p></div></article>`); });

    const title = document.getElementById('heroTitle');
    title.innerHTML = title.innerText.split(' ').map(w=>`<span class="inline-block mr-3">${w}</span>`).join('');
    gsap.from('#heroTitle span',{y:70,opacity:0,rotate:4,duration:.75,stagger:.05,ease:'back.out(1.6)'});
    gsap.utils.toArray('.reveal,.service-card,.country-card,.step-card,blockquote').forEach((el,i)=> gsap.from(el,{y:65,opacity:0,duration:.8,delay:i*.03,scrollTrigger:{trigger:el,start:'top 86%'}}));
    gsap.to('.step-card',{opacity:.75,yoyo:true,repeat:-1,stagger:.25,duration:1.2,ease:'sine.inOut'});
    gsap.to('#guaranteeRing',{rotation:360,repeat:-1,duration:5,ease:'none'});

    document.querySelectorAll('.counter').forEach(el=>{ const target=+el.dataset.target; ScrollTrigger.create({trigger:el,start:'top 90%',once:true,onEnter:()=>{const o={v:0};gsap.to(o,{v:target,duration:1.8,onUpdate:()=>el.textContent=Math.floor(o.v)})}}) });
    ScrollTrigger.create({trigger:'#impact',start:'top 75%',once:true,onEnter:()=>{const o={v:0};gsap.to(o,{v:51,duration:2.1,onUpdate:()=>impactCount.textContent=Math.floor(o.v)})}});

    exploreBtn.onclick=()=>gsap.to(window,{duration:1.1,scrollTo:'#destinations',ease:'power2.inOut'});
    confidenceBtn.onclick=()=>gsap.to(window,{duration:1.1,scrollTo:'#home',ease:'power2.inOut'});

    window.addEventListener('scroll',()=>{ const p=(window.scrollY/(document.body.scrollHeight-innerHeight))*100; progressLine.style.width=`${p}%`; header.classList.toggle('scale-[.97]',window.scrollY>40); [...document.querySelectorAll('main section')].forEach(sec=>{ if(window.scrollY>=sec.offsetTop-160&&window.scrollY<sec.offsetTop+sec.offsetHeight-160){ document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('text-accent',a.getAttribute('href')==='#'+sec.id)); } }); });

    document.querySelectorAll('.faq-btn').forEach(btn=>btn.addEventListener('click',()=>{ const panel=btn.nextElementSibling,open=panel.style.maxHeight; document.querySelectorAll('.faq-content').forEach(p=>p.style.maxHeight=null); panel.style.maxHeight=open?null:panel.scrollHeight+'px'; }));

    menuBtn.onclick=()=>{mobileMenu.classList.remove('hidden');menuBtn.setAttribute('aria-expanded','true');}; closeMenu.onclick=()=>{mobileMenu.classList.add('hidden');menuBtn.setAttribute('aria-expanded','false');}; document.querySelectorAll('.mobile-link').forEach(l=>l.onclick=()=>{mobileMenu.classList.add('hidden');menuBtn.setAttribute('aria-expanded','false');});
    let s=0; setInterval(()=>{s=(s+1)%3;storyCarousel.style.transform=`translateX(-${s*100}%)`},4000);

    const countryModal = document.getElementById('countryModal'), countryCard = document.getElementById('countryModalCard');
    grid.addEventListener('click',(e)=>{ const card=e.target.closest('[data-country]'); if(!card) return; const data = destinations.find(d=>d.key===card.dataset.country); countryHero.src=data.image; countryTitle.textContent=`${data.name} ${data.flag}`; countryWhy.textContent=data.why; countryScholarships.textContent=data.scholarships; countryWork.textContent=data.work; countryStability.textContent=data.stability; countryLife.textContent=data.life; universityGrid.innerHTML = data.unis.map(u=>`<article class="glass rounded-xl p-4 hover:-translate-y-1 hover:shadow-glow transition"><h5 class="font-semibold text-navy">${u[0]}</h5><p class="text-sm text-gray-700 mt-2">${u[1]}</p></article>`).join(''); countryModal.classList.remove('hidden'); document.body.classList.add('modal-open'); gsap.fromTo(countryCard,{opacity:0,scale:.95,y:20},{opacity:1,scale:1,y:0,duration:.45,ease:'power2.out'}); });
    const closeCountryModal = ()=>{ gsap.to(countryCard,{opacity:0,scale:.95,duration:.25,onComplete:()=>{countryModal.classList.add('hidden');document.body.classList.remove('modal-open')}})};
    document.querySelector('.modal-close').onclick=closeCountryModal; countryModal.addEventListener('click',(e)=>{ if(e.target===countryModal) closeCountryModal(); });

    const consultModal = document.getElementById('consultModal'), consultCard = document.getElementById('consultCard');
    const openConsult = ()=>{ consultModal.classList.remove('hidden');document.body.classList.add('modal-open');gsap.fromTo(consultCard,{opacity:0,scale:.95,y:20},{opacity:1,scale:1,y:0,duration:.45});gsap.from('#consultForm > *',{opacity:0,y:16,stagger:.05,duration:.35,delay:.12}); };
    const closeConsult = ()=> gsap.to(consultCard,{opacity:0,scale:.95,duration:.25,onComplete:()=>{consultModal.classList.add('hidden');document.body.classList.remove('modal-open')}});
    bookBtnHero.onclick=openConsult; bookBtnTop.onclick=openConsult; bookBtnMobile.onclick=()=>{mobileMenu.classList.add('hidden');openConsult();}; document.querySelector('.consult-close').onclick=closeConsult; consultModal.addEventListener('click',(e)=>{ if(e.target===consultModal) closeConsult(); });

    document.addEventListener('keydown',(e)=>{ if(e.key==='Escape' && !countryModal.classList.contains('hidden')) closeCountryModal(); if(e.key==='Escape' && !consultModal.classList.contains('hidden')) closeConsult(); if(e.key==='Escape') document.querySelectorAll('#termsModal,#privacyModal').forEach(m=>m.classList.add('hidden')); });

    termsBtn.onclick=()=>{termsModal.classList.remove('hidden');document.body.classList.add('modal-open');}; privacyBtn.onclick=()=>{privacyModal.classList.remove('hidden');document.body.classList.add('modal-open');}; document.querySelectorAll('.legal-close').forEach(btn=>btn.onclick=()=>{document.getElementById(btn.dataset.target).classList.add('hidden');document.body.classList.remove('modal-open');}); [termsModal,privacyModal].forEach(mod=>mod.addEventListener('click',e=>{if(e.target===mod){mod.classList.add('hidden');document.body.classList.remove('modal-open');}}));

    appLevel.addEventListener('change',()=>{ const v=appLevel.value; if(v==='Bachelor') dynamicUploads.innerHTML = `<label class="drop-zone rounded-xl p-4 block">Grade 10 & 12 National Exams<input type="file" class="mt-2 w-full text-sm" multiple /></label>`; else if(v==='Masters') dynamicUploads.innerHTML = `<div class="grid md:grid-cols-2 gap-4"><label class="drop-zone rounded-xl p-4 block">Bachelor Degree Certificate<input type="file" class="mt-2 w-full text-sm" multiple /></label><label class="drop-zone rounded-xl p-4 block">Bachelor Transcript/Student Copy<input type="file" class="mt-2 w-full text-sm" multiple /></label></div>`; else dynamicUploads.innerHTML = ''; gsap.from('#dynamicUploads .drop-zone',{opacity:0,y:10,stagger:.08,duration:.3}); });
    consultForm.addEventListener('submit',(e)=>{e.preventDefault();gsap.fromTo(e.submitter,{scale:1},{scale:.96,yoyo:true,repeat:1,duration:.09});});
});
